spring:
  application:
    name: activityservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/travel_sathi_trip_db
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  exchange:
    name: activity.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking