spring:
  application:
    name: apigateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/travelsathi-48e5d
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: userservice
              uri: lb://USERSERVICE
              predicates:
                - Path=/api/v1/users/**

            - id: aiservice
              uri: lb://AISERVICE
              predicates:
                - Path=/api/v1/recommendations/**

            - id: activityservice
              uri: lb://ACTIVITYSERVICE
              predicates:
                - Path=/api/v1/trips/**

server:
  port: 8005

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/