spring:
  application:
    name: userservice

  datasource:
    url: jdbc:mysql://localhost:3306/travel_sathi_user_dB
    username: root
    password: x

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/