spring:
  application:
    name: activityservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/travel_sathi_trip_db
server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/